### PR TITLE
Initial Schema

### PR DESCRIPTION
**Pull request by Neitsch**

### CODE REVIEW

**Review by infobiac — COMMENTED** [review]
On a django project, generally all models should live within specific apps (i.e. here we should first startapp stockmodeler or something), in order to keep organization clear.

**Review by infobiac — CHANGES_REQUESTED** [review]
See my comment

**Comment by Neitsch** [comment]
Oh, so the models are a separate app?

**Comment by infobiac** [comment]
In this case I think it would make sense for us to have a "historical performance stock app", and an "investment/connection to wells fargo data app" given that they do pretty different things, and then the point of entry (buy bitcoin) just serves as a router to the two. Auth could theoretically be a third app, or we can leave it within buy bitcoin. In which case I would think that these models should go in the "historical performance stock app". That way the architecture is very well defined, and the views don't become too crowded.

**Review by infobiac — APPROVED** [review]

**Pull request merged**
