### PR TITLE
modified auth page

### PR DESCRIPTION
**Pull request by julyanserra**
new login page, let me know what if anything needs to be changed

### CODE REVIEW

**Comment by julyanserra** [comment]
screen shot 2017-10-24 at 1 33 06 am

**Review by jomivega — APPROVED** [review]
Looks good :)

**Comment by jomivega** [comment]
Out of curiosity, how does it behave on mobile? Can always change after demo

**Comment by julyanserra** [comment]
mobile not great, next PR ill make responsive
screen shot 2017-10-24 at 2 01 31 am

**Comment by jomivega** [comment]
Love the creativity and marketing skills. You're a pimp daddy

**Comment by Neitsch** [comment]
Please remove the .DS_Store file

**Pull request merged**
