### PR TITLE
User balance

### PR DESCRIPTION
**Pull request by infobiac**
Gets all user balances, returns in json

### CODE REVIEW

**Review by Neitsch — COMMENTED** [review]
* Could we also have this as a GraphQL endpoint?
* What is the shape of the response?

**Comment by infobiac** [comment]
What do you mean by shape?

**Comment by Neitsch** [comment]
{
  field1: [],
  ...
}

**Comment by infobiac** [comment]
{
"Plaid Diamond 12.5% APR Interest Credit Card": "-410", 
"Plaid Gold Standard 0% Interest Checking": 100, 
"Plaid Silver Standard 0.1% Interest Saving": 200, 
"Plaid Bronze Standard 0.2% Interest CD": 1000
}
Noticing now there's a type mismatch. Fixing.

**Comment by infobiac** [comment]
updated:
{"Plaid Diamond 12.5% APR Interest Credit Card": -410, "Plaid Silver Standard 0.1% Interest Saving": 200, "Plaid Bronze Standard 0.2% Interest CD": 1000, "Plaid Gold Standard 0% Interest Checking": 100}

**Comment by Neitsch** [comment]
Probably something like
```
[
  {
    name: "Plaid Diamond 12.5% APR Interest Credit Card",
    balance: -410,
    currency: "$"
  },
  ...
]
```
Since that should not be a key with whitespaces (chance of duplicates etc). Seems more robust...

**Comment by infobiac** [comment]
Makes sense; done. Didn't use currency because all currencies are usd, but added account type:
[{"balance": 100, "type": "checking", "name": "Plaid Gold Standard 0% Interest Checking"}, {"balance": 200, "type": "savings", "name": "Plaid Silver Standard 0.1% Interest Saving"}, {"balance": 1000, "type": "cd", "name": "Plaid Bronze Standard 0.2% Interest CD"}, {"balance": -410, "type": "credit card", "name": "Plaid Diamond 12.5% APR Interest Credit Card"}]

**Review by Neitsch — APPROVED** [review]
Preferably add GraphQL as well, but we can do that later

**Pull request merged**
