### PR TITLE
documentation build v1

### PR DESCRIPTION
**Pull request by infobiac**
to be hosted on github pages

### CODE REVIEW

**Comment by infobiac** [comment]
Relevant files: index.rst, authentication.rst, stocks.rst, trading.rst, web.rst, conf.py (files are at bottom)

**Review by Neitsch — CHANGES_REQUESTED** [review]
Not a big fan of committing everything. Can we push to github pages? Maybe something like this? https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by infobiac** [comment]
The main issue is that this is unfortunately not doable as an automated script; it has to be generated manually. Sphinx forces you to name individual files, rather than being able to specify a top-level directory to find documentation from. So although we could automate it, we'd still have to go in and manually modify...

**Comment by Neitsch** [comment]
Can we close this based on #159 ?

**Pull request closed without merging**
