### PR TITLE
Adding missing tests

### PR DESCRIPTION
**Pull request by jomivega**

### CODE REVIEW

**Comment by Neitsch** [comment]
How come this works? I'd expect this to fail, since we need plaid to retrieve the available balance. Is there an error in the implementation? @infobiac

**Review by Neitsch — COMMENTED** [review]
Generally I approve of the PR. After discussion on Slack, we should probably rename the method, since it is very misleading. What do you think of `trading_balance()`, thereby indicating, that it only calculates the + or - achieved through trading.

**Review by Neitsch — DISMISSED** [review]
Please address comment

**Comment by jomivega** [comment]
Sounds good. Will do this afternoon.

**Review by infobiac — APPROVED** [review]

**Pull request merged**
